package com.xxx.otrs.mapper.ticket;

import java.util.List;
import java.util.Map;

import com.xxx.otrs.domain.ticket.Ticket;
import com.xxx.util.sql.Criteria;

public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insertSelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    Ticket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKeySelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKey(Ticket record);
    
    
    List<Ticket> query(Criteria criteria);
    
    
    /**
     * 查询工单
     * @param criteria
     * @return
     */
    List<Map<String,Object>> queryTicket(Criteria criteria);
    
    
    
    /**
     * 获得每个队列工单数
     * @param criteria
     * @return
     */
    List<Map<String,Object>> getQueueTicketAmount(Criteria criteria);
    
    
    
    /**
     * 统计柱形图数据
     * @return
     */
    List<Map<String,Object>> countBar();
    
    
    
    /**
     * 统计当前月 每天 每个队列 未关闭工单数
     * 通过队列和天 进行分组
     * @return
     */
    List<Map<String,Object>> currentMonthTicket();
    
    /**
     * 获得每天创建的工单总数
     * @return
     */
    List<Map<String,Object>> findEveryDayCreateSum();
    
    
    /**
     * 获得每天关闭的工单总数
     * @return
     */
    List<Map<String,Object>> findEveryDayCloseSum();
    
    
    /**
     * 获得每天升级的工单总数
     * @return
     */
    List<Map<String,Object>> findEveryDayGradeSum();
    
    
    
    
}