package com.xxx.wxi.domain.base;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_account.login_id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_account.login_name
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_account.login_password
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String loginPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_account.login_id
     *
     * @return the value of dtwx_account.login_id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_account.login_id
     *
     * @param loginId the value for dtwx_account.login_id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_account.login_name
     *
     * @return the value of dtwx_account.login_name
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_account.login_name
     *
     * @param loginName the value for dtwx_account.login_name
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_account.login_password
     *
     * @return the value of dtwx_account.login_password
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_account.login_password
     *
     * @param loginPassword the value for dtwx_account.login_password
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }
}