package com.xxx.wxi.domain.base;

public class AgentCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_agent_cfg.cfgid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private Integer cfgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_agent_cfg.app_type
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_agent_cfg.cfg_key
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String cfgKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_agent_cfg.cfg_value
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String cfgValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_agent_cfg.descr
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String descr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_agent_cfg.cfgid
     *
     * @return the value of dtwx_agent_cfg.cfgid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public Integer getCfgid() {
        return cfgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_agent_cfg.cfgid
     *
     * @param cfgid the value for dtwx_agent_cfg.cfgid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setCfgid(Integer cfgid) {
        this.cfgid = cfgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_agent_cfg.app_type
     *
     * @return the value of dtwx_agent_cfg.app_type
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_agent_cfg.app_type
     *
     * @param appType the value for dtwx_agent_cfg.app_type
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_agent_cfg.cfg_key
     *
     * @return the value of dtwx_agent_cfg.cfg_key
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getCfgKey() {
        return cfgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_agent_cfg.cfg_key
     *
     * @param cfgKey the value for dtwx_agent_cfg.cfg_key
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setCfgKey(String cfgKey) {
        this.cfgKey = cfgKey == null ? null : cfgKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_agent_cfg.cfg_value
     *
     * @return the value of dtwx_agent_cfg.cfg_value
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getCfgValue() {
        return cfgValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_agent_cfg.cfg_value
     *
     * @param cfgValue the value for dtwx_agent_cfg.cfg_value
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setCfgValue(String cfgValue) {
        this.cfgValue = cfgValue == null ? null : cfgValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_agent_cfg.descr
     *
     * @return the value of dtwx_agent_cfg.descr
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_agent_cfg.descr
     *
     * @param descr the value for dtwx_agent_cfg.descr
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }
}