package com.xxx.wxi.domain.base;

public class AppConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_app_config.id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_app_config.app_id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_app_config.config_key
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_app_config.config_value
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_app_config.description
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_app_config.id
     *
     * @return the value of dtwx_app_config.id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_app_config.id
     *
     * @param id the value for dtwx_app_config.id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_app_config.app_id
     *
     * @return the value of dtwx_app_config.app_id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_app_config.app_id
     *
     * @param appId the value for dtwx_app_config.app_id
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_app_config.config_key
     *
     * @return the value of dtwx_app_config.config_key
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_app_config.config_key
     *
     * @param configKey the value for dtwx_app_config.config_key
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_app_config.config_value
     *
     * @return the value of dtwx_app_config.config_value
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_app_config.config_value
     *
     * @param configValue the value for dtwx_app_config.config_value
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_app_config.description
     *
     * @return the value of dtwx_app_config.description
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_app_config.description
     *
     * @param description the value for dtwx_app_config.description
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}