package com.xxx.wxi.domain.base;

public class Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_content.msgid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_content.openid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_content.state
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dtwx_content.content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_content.msgid
     *
     * @return the value of dtwx_content.msgid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_content.msgid
     *
     * @param msgid the value for dtwx_content.msgid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_content.openid
     *
     * @return the value of dtwx_content.openid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_content.openid
     *
     * @param openid the value for dtwx_content.openid
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_content.state
     *
     * @return the value of dtwx_content.state
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_content.state
     *
     * @param state the value for dtwx_content.state
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dtwx_content.content
     *
     * @return the value of dtwx_content.content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dtwx_content.content
     *
     * @param content the value for dtwx_content.content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}