package com.xxx.wxi.mapper.base;

import com.xxx.wxi.domain.base.Account;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_account
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_account
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_account
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_account
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    Account selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_account
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_account
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKey(Account record);
}