package com.xxx.wxi.mapper.base;

import java.util.List;

import com.xxx.util.sql.Criteria;
import com.xxx.wxi.domain.base.AgentCfg;

public interface AgentCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_agent_cfg
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int deleteByPrimaryKey(Integer cfgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_agent_cfg
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insert(AgentCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_agent_cfg
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insertSelective(AgentCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_agent_cfg
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    AgentCfg selectByPrimaryKey(Integer cfgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_agent_cfg
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKeySelective(AgentCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_agent_cfg
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKey(AgentCfg record);
    
    List<AgentCfg> query(Criteria criteria);
}