package com.xxx.wxi.mapper.base;

import com.xxx.wxi.domain.base.AppConfig;

public interface AppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_app_config
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_app_config
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_app_config
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insertSelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_app_config
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    AppConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_app_config
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKeySelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_app_config
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKey(AppConfig record);
}