package com.xxx.wxi.mapper.base;

import com.xxx.wxi.domain.base.Content;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int deleteByPrimaryKey(String msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insert(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int insertSelective(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    Content selectByPrimaryKey(String msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKeySelective(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dtwx_content
     *
     * @mbggenerated Tue Aug 29 09:39:59 CST 2017
     */
    int updateByPrimaryKey(Content record);
}