package com.xxx.wxi.mapper.base;

import java.util.List;

import com.xxx.util.sql.Criteria;
import com.xxx.wxi.domain.base.Remark;

public interface RemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated Fri Oct 13 15:20:06 CST 2017
     */
    int deleteByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated Fri Oct 13 15:20:06 CST 2017
     */
    int insert(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated Fri Oct 13 15:20:06 CST 2017
     */
    int insertSelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated Fri Oct 13 15:20:06 CST 2017
     */
    Remark selectByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated Fri Oct 13 15:20:06 CST 2017
     */
    int updateByPrimaryKeySelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated Fri Oct 13 15:20:06 CST 2017
     */
    int updateByPrimaryKey(Remark record);
    
    
    List<Remark> query(Criteria criteria);
    
    List<Remark> queryRemark();
}